/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface2.h"
#include <stdlib.h>  
#include <stdbool.h> 

int   band1, band2, band3;
CLIENT *clnt;

const char *roles[] = {"Administrativo", "Docente", "Estudiante"};

bool validarLongitud(char *cadena)
{
    int longitud = strlen(cadena);
    return (longitud >= 8 && longitud <= 15);
}

bool validarLongitud8(char *cadena)
{
    int longitud = strlen(cadena);
    return (longitud == 8);
}

bool validarRepetido(char *codigo)
{
    nodo_usuario *result_aux;
    result_aux = consultarusuario_1(&codigo, clnt);
    if (strcmp(result_aux->codigo, "-1") == 0)
    {
        return false;
    }
}

nodo_administrador *solicitar_login(){
    char usuario[MAXLOGIN]; 
    char clave[MAXLOGIN];   
    int bandera;
    nodo_administrador *admin_user = malloc(sizeof(nodo_administrador));
    if (admin_user == NULL) {
        printf("Error: No se pudo asignar memoria para admin_user\n");
        exit(1);
    }
    
    do
    {
        bandera = 0;
        printf("\n\n========== LOGIN ==========");
        printf("\n Ingrese su usuario: ");
        scanf("%s", usuario);
        printf("\n Ingrese su clave: ");
        scanf("%s", clave);
        if ( !validarLongitud(usuario) || !validarLongitud(clave))
        {
            printf("El usuario y clave deben tener entre 8 y 15 caracteres!.\n");
            bandera = 1;
        }
        
    } while (bandera != 0);
    
    // Copiar el usuario y la clave ingresados al nodo_administrador
    strcpy(admin_user->usuario, usuario);
    strcpy(admin_user->clave, clave);
    
    return admin_user; 
}


void autorizar_usuarios_1(char *host)
{
    bool_t *result_1;
    nodo_usuario registrarusuariosistema_1_arg;
    bool_t *result_2;
    char *borrarusuariosistema_1_arg;
    nodo_usuario *result_3;
    char *consultarusuario_1_arg;
    bool_t *result_4;
    nodo_administrador iniciar_sesion_1_arg;

    char *codigo;
    int opcion;
#ifndef DEBUG
    clnt = clnt_create(host, autorizar_usuarios, autorizar_usuarios_version, "udp");
    if (clnt == NULL)
    {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif /* DEBUG */
    

    do
    {
        band3 = 0;
        
        iniciar_sesion_1_arg = *solicitar_login();
        if (*iniciar_sesion_1(&iniciar_sesion_1_arg, clnt))
        {
            band3 = 1;
        }else{
            printf("\n-Usuario o clave incorrecto(a).\n");
        }
    } while (band3 != 1);

    do
    {
        printf("\n\n========== Menú ==========");
        printf("\n 1. Registrar usuario");
        printf("\n 2. Consultar usuario");
        printf("\n 3. Borrar usuario");
        printf("\n 4. Salir");
        printf("\n==========================");

        printf("\n Digite opción: ");
        scanf("%d", &opcion);

        switch (opcion)
        {
        case 1:
            int rol_opcion = 0;
            do
            {
                band1 = 0;
                printf("\n----- Registrar Usuario -----");
                printf("\n-Digite el codigo: ");
                scanf("%s", registrarusuariosistema_1_arg.codigo);

                if (!validarLongitud8(registrarusuariosistema_1_arg.codigo))
                {
                    printf("¡El codigo debe tener 8 caracteres exactamente!.\n");
                    band1 = 1;
                }

                if (validarRepetido(registrarusuariosistema_1_arg.codigo))
                {
                    printf("¡El usuario con codigo %s ya existe!.\n", registrarusuariosistema_1_arg.codigo);
                    band1 = 1;
                }

            } while (band1 != 0);

            printf("\n-Digite el nombre del usuario: ");
            scanf("%s", registrarusuariosistema_1_arg.nombres);
            printf("\n-Digite el apellido del usuario: ");
            scanf("%s", registrarusuariosistema_1_arg.apellidos);

            do
            {
                band2 = 0;
                printf("\n-Digite el rol del usuario: \n1)Administrativo\n2)Docente\n3)Estudiante\nSeleccione una opcion:");
                scanf("%d", &rol_opcion);
                switch (rol_opcion)
                {
                case 1:
                    strcpy(registrarusuariosistema_1_arg.rol, roles[rol_opcion - 1]);
                    break;
                case 2:
                    strcpy(registrarusuariosistema_1_arg.rol, roles[rol_opcion - 1]);
                    break;
                case 3:
                    strcpy(registrarusuariosistema_1_arg.rol, roles[rol_opcion - 1]);
                    break;
                default:
                    printf("\nOpcion invalida.");
                    band2 = 1;
                    break;
                }

            } while (band2 != 0);

            result_1 = registrarusuariosistema_1(&registrarusuariosistema_1_arg, clnt);
            if (result_1 == (bool_t *)NULL)
            {
                clnt_perror(clnt, "call failed");
            }
            else if (*result_1 == TRUE)
            {
                printf("\n¡Usuario registrado exitosamente!\n");
            }
            else
            {
                printf("\n Usuario no registrado");
            }

            break;
        case 2:
            printf("\n----- Consultar Usuario -----");
            codigo = (char *)malloc(sizeof(char) * 20);
            printf("\n-Digite el codigo del usuario:");
            scanf("%s", codigo);
            result_3 = consultarusuario_1(&codigo, clnt);
            if (result_3 == (nodo_usuario *)NULL)
            {
                clnt_perror(clnt, "call failed");
            }
            else if (strcmp(result_3->codigo, "-1") == 0)
            {
                printf("\nNo existe el usuario con codigo %s.", codigo);
            }
            else
            {
                printf("\nCodigo: %s", result_3->codigo);
                printf("\nNombres: %s", result_3->nombres);
                printf("\nApellidos: %s", result_3->apellidos);
                printf("\nRol: %s", result_3->rol);
            }
            free(codigo);
            break;
        case 3:
            printf("\n----- Borrar Usuario -----");
            codigo = (char *)malloc(sizeof(char) * 20);
            printf("\n-Digite el codigo del usuario:");
            scanf("%s", codigo);
            result_3 = consultarusuario_1(&codigo, clnt);
            if (result_3 == (nodo_usuario *)NULL)
            {
                clnt_perror(clnt, "call failed");
            }
            else if (strcmp(result_3->codigo, "-1") == 0)
            {
                printf("\nNo existe el usuario con codigo %s.", codigo);
            }
            else
            {
                int borrar = 0;
                printf("\nEstá seguro que desea borrar el usuario?: \n1)Si\n2)No\n Seleccione una opcion:", codigo);
                scanf("%d", &borrar);
                switch (borrar)
                {
                case 1:
                    result_2 = borrarusuariosistema_1(&codigo, clnt);
                    free(codigo);
                    if (result_2 == (bool_t *)NULL)
                    {
                        clnt_perror(clnt, "call failed");
                    }
                    else if (*result_2 == TRUE)
                    {
                        printf("Usuario eliminado exitosamente!\n");
                    }
                    break;
                case 2:
                    break;
                default:
                    printf("\nOpcion invalida.");
                    break;
                }
            }

            break;
        case 4:
            printf(" Saliendo...\n");
            clnt_destroy(clnt);
            exit(0);
            break;
        default:
            printf("\nOpción invalida.");
            break;
        }

    } while (opcion != 4);

    result_1 = registrarusuariosistema_1(&registrarusuariosistema_1_arg, clnt);
    if (result_1 == (bool_t *)NULL)
    {
        clnt_perror(clnt, "call failed");
    }
    result_2 = borrarusuariosistema_1(&borrarusuariosistema_1_arg, clnt);
    if (result_2 == (bool_t *)NULL)
    {
        clnt_perror(clnt, "call failed");
    }
    result_3 = consultarusuario_1(&consultarusuario_1_arg, clnt);
    if (result_3 == (nodo_usuario *)NULL)
    {
        clnt_perror(clnt, "call failed");
    }
    result_4 = iniciar_sesion_1(&iniciar_sesion_1_arg, clnt);
    if (result_4 == (bool_t *)NULL)
    {
        clnt_perror(clnt, "call failed");
    }
#ifndef DEBUG
    clnt_destroy(clnt);
#endif /* DEBUG */
}



int main(int argc, char *argv[])
{
    char *host;

    if (argc < 2)
    {
        printf("usage: %s server_host\n", argv[0]);
        exit(1);
    }
    host = argv[1];
    autorizar_usuarios_1(host);
    exit(0);
}
