/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface1.h"


void
autorizar_usuarios1_1(char *host)
{
	CLIENT *clnt;
	nodo_respuesta1  *result_1;
	char * solicitarentrada_1_arg;
	nodo_respuesta1  *result_2;
	char * solicitarsalida_1_arg;
	usuarios  *result_3;
	char *listarusuarios_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, autorizar_usuarios1, autorizar_usuarios_version1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	
	result_3 = listarusuarios_1((void*)&listarusuarios_1_arg, clnt);
	if (result_3 == (usuarios *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("Código: %s\n", result_3->);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	autorizar_usuarios1_1 (host);
exit (0);
}
